---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/main/action
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/main/app/go
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: src/main/app/go
    schedule:
      interval: daily
