---
name: Semantic Version Github Action
description: Github Action to streamline Release Workflows with Semantic Version Validation for Accurate and Consistent Versioning
inputs:
  command:
    description: The semver command that should be run
    default: ""
    required: true
  version:
    description: The Version, that should be passed to the semver command
    default: ""
    required: true
  flags:
    description: Flags to pass to the semver command (optional)
    default: ""
    required: false
runs:
  using: 'docker'
  image: 'src/main/Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.version }}
    - ${{ inputs.flags }}
