---
name: Semantic Version Github Action
description: Github Action to adjust version information in antora.yml depending on current branch or version tag.
inputs:
  command:
    description: The semver command that should be run
    default: ""
    required: true
runs:
  using: 'docker'
  image: 'src/main/Dockerfile'
  args:
    - ${{ inputs.command }}
