---
name: Semantic Version Github Action
description: Github Action to streamline Release Workflows with Semantic Version Validation for Accurate and Consistent Versioning
inputs:
  command:
    description: The semver command that should be run
    default: ""
    required: true
runs:
  using: 'docker'
  image: 'src/main/Dockerfile'
  args:
    - ${{ inputs.command }}
