---
version: "3.3"
services:

  init:
    image: golang:1.20.6-alpine3.18
    container_name: init
    user: ${MY_UID}:${MY_GID}
    volumes: &volumes
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /home/${MY_USERNAME}/.cache:/home/${MY_USERNAME}/.cache:rw #? ?????????????
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        go mod init github.com/sommerfeld-io/semver
        go mod tidy
        go get github.com/spf13/cobra@v1.7.0
        go get github.com/Masterminds/semver@v1.5.0
        go fmt ./...

  test:
    image: golang:1.20.6-alpine3.18
    container_name: test
    depends_on:
      init:
        condition: service_completed_successfully
    user: ${MY_UID}:${MY_GID}
    volumes: *volumes
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        go test -coverprofile=go-code-coverage.out ./...

  build:
    build: .
    image: local/semver:dev
    container_name: build
    depends_on:
      test:
        condition: service_completed_successfully
    user: ${MY_UID}:${MY_GID}
    volumes: *volumes
    working_dir: /app

  run-1: &run-config
    image: local/semver:dev
    container_name: run-1
    depends_on:
      build:
        condition: service_completed_successfully
    user: ${MY_UID}:${MY_GID}
    command: validate v0.1.0

  run-2:
    <<: *run-config
    container_name: run-2
    command: validate v0.1.0-SNAPSHOT

  run-3:
    <<: *run-config
    container_name: run-3
    command: validate 0.1.0-SNAPSHOT

  run-4:
    <<: *run-config
    container_name: run-4
    command: validate 0.1.0-SNAPSHOT --show-errors

  # cleanup:
  #   image: alpine:3.18.2
  #   container_name: cleanup
  #   depends_on:
  #     test:
  #       condition: service_completed_successfully
  #   user: ${MY_UID}:${MY_GID}
  #   volumes: *volumes
  #   working_dir: /app
  #     - /bin/sh
  #     - -c
  #     - |
  #       rm -f go-code-coverage.out
