Github Action to streamline Release workflows with Semantic Version validation for accurate and consistent versioning.

image:{github-actions-url}/{job-generate-docs}/{badge}[Github Badge, link={github-actions-url}/{job-generate-docs}]
image:{github-actions-url}/{job-ci}/{badge}[Github Badge, link={github-actions-url}/{job-ci}]

== About this project
The semver-action repository provides a GitHub Action that enables the validation of semantic versions in all Deploy + Release workflows used within the sommerfeld-io organization. This action helps ensure consistent and accurate versioning across projects by enforcing the rules defined in the link:https://semver.org[Semantic Versioning 2.0.0] specification.

By incorporating the `semver-action` into the `Deploy + Release workflows` of all repositories in the sommerfeld-io organization, software projects can ensure consistent and accurate semantic versioning, contributing to improved release processes and efficient collaboration.

* Github Repository -> {url-project}
* Where to file issues -> {url-project}/issues
* Sonar -> https://sonarcloud.io/project/overview?id=sommerfeld-io_semver-action

=== About Semantic Versioning
Semantic versions are applied in the link:https://github.com/sommerfeld-io[sommerfeld-io GitHub organization]. All Versions follow the pattern `major.minor.bugfix` for stable versions (e.g. `v0.1.2`) and `major.minor.bugfix-SNAPSHOT` for unstable versions, that are still under active development (e.g. `v0.1.2-SNAPSHOT`). The leading `v` in lowercase is mandatory.

See link:https://github.com/sommerfeld-io/semver-action/blob/main/src/main/app/services/validate_service_test.go[src/main/app/services/validate_service_test.go] for details on allow and forbidden version patterns.

== How to use this project
The `semver-action` is specifically designed as a GitHub Actions workflow action, intended to be integrated into workflows. It is specifically utilized as part of the "Deploy + Release workflows" within the link:https://github.com/sommerfeld-io[sommerfeld-io GitHub organization]. However, the Dockerfile used in this action can also be employed independently for other purposes, allowing for versatile and standalone usage beyond GitHub Actions workflows.

=== Use in Github Actions Workflows 
[source, yml]
----
# [...]
jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      # [...]
      - name: Validate version
        uses: sommerfeld-io/semver-action@main
        with:
          command: validate
          version: ${{ github.event.inputs.version }}
          flags: --json
# [...]
----

==== Inputs
[cols="1,3,>1",options="header"]
|===
|Param |Description |Required
|command |The semver command that should be run |true
|version |The Version, that should be passed to the semver command |true
|flags |Flags to pass to the semver command (optional) |false
|===

For information about all available commands, run `docker run --rm sommerfeldio/semver:latest`. This will show the applications help.

==== Outputs
_No outputs specified._

=== Use Docker image outside of Github Actions
The Docker image of the "semver-action" is not only used internally for GitHub Actions workflows but is also link:https://hub.docker.com/r/sommerfeldio/semver[published to DockerHub]. For standalone usage of the Docker image, run `docker run --rm local/semver:dev` (showing the applications help) or `docker run --rm local/semver:dev validate v.1.0` to validate a version against semantic versioning rules.

== Risks and Technical Debts
link:{url-project}/issues?q=is%3Aissue+label%3Asecurity%2Crisk+is%3Aopen[All issues labeled as risk (= some sort of risk or a technical debt) or security (= related to security issues)] are tracked as Github issue and carry the respective label.

== Contact
Feel free to contact me via sebastian@sommerfeld.io or visit my website https://www.sommerfeld.io.
