---
name: CI

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches-ignore:
      - dependabot/**
  schedule:
    - cron: '0 3 * * 1' # https://crontab.guru/#0_2_*_*_1

env:
  IMAGE: sommerfeldio/semver

permissions:
  contents: read

jobs:
  module-ci-lint:
    uses: sommerfeld-io/.github/.github/workflows/module-ci-lint.yml@main

  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/main/Dockerfile

  ci-go-app:
    runs-on: ubuntu-latest
    needs: ['module-ci-lint', 'lint-dockerfile']
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.6'
      - name: Test go app
        run: |
          (
            cd src/main/app || exit
            readonly COVERAGE_REPORT="go-code-coverage.out"

            go test -coverprofile="$COVERAGE_REPORT" ./...

            old='github.com/sommerfeld-io/semver'
            new='src/main/app'
            sed -i "s|$old|$new|g" "$COVERAGE_REPORT"
          )
        shell: bash
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ci-docker:
    runs-on: ubuntu-latest
    needs: ci-go-app
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set docker tag ('ci' for main or feature branch)
        id: vars
        run: |
          echo ${{ github.ref }}

          TAG='ci'

          echo "tag = $TAG"
          echo "DOCKER_TAG=$TAG" >> $GITHUB_OUTPUT
        shell: bash
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker image build
        uses: docker/build-push-action@v4
        with:
          context: src/main
          platforms: linux/amd64
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: ${{ env.IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }}

  test-docker:
    runs-on: ubuntu-latest
    needs: ci-docker
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test go app
        run: |
          docker pull ${{ env.IMAGE }}:ci # TODO get tag dynamically from previous job somwhow !!!!!!!!!!
          docker run ${{ env.IMAGE }}:ci
          echo "TODO ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ..."
          echo "TODO ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ..."
          echo "TODO ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ..."
        shell: bash

  on-failure:
    runs-on: ubuntu-latest
    needs: ['module-ci-lint', 'lint-dockerfile', 'ci-docker', 'ci-go-app', 'test-docker']
    if: failure()

    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
